apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-pv
spec:
    capacity: 20Gi
    accessModes:
    - ReadWriteMany
    PersistentVolumeReclaimPolicy: Retain
    nfs:
        path: /data
        server: 172.17.0.1
        readOnly: false
